# Generated by Django 4.0 on 2021-12-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
