# Generated by Django 4.0 on 2022-01-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_category_options_answer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image_url',
            field=models.CharField(default='https://drive.google.com/file/d/14fX5yGbI0xrApvbx58fXkqequoyBSY9Z/view?usp=sharing', max_length=255, verbose_name='image_url'),
        ),
    ]
