# Generated by Django 4.0 on 2022-01-03 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_answer_color_alter_answer_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='color',
        ),
    ]
