# Generated by Django 4.0 on 2022-01-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.CharField(default='', max_length=255, verbose_name='Comment Text'),
        ),
    ]
