# Generated by Django 4.0 on 2022-01-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_alter_question_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Survey Title'),
        ),
    ]
