# Generated by Django 4.0 on 2022-01-10 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_alter_survey_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reply', to='survey.answer'),
        ),
        migrations.CreateModel(
            name='FinalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_comment', models.CharField(default='', max_length=255, verbose_name='Final Comment Text')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey', to='survey.survey')),
            ],
            options={
                'verbose_name': 'Final Comment',
                'verbose_name_plural': 'Final Comments',
                'ordering': ['id'],
            },
        ),
    ]
