# Generated by Django 4.0 on 2022-02-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_finalcomment_knowledge_scale_finalcomment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
    ]
