# Generated by Django 4.0 on 2022-02-07 03:57

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_alter_survey_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalcomment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 7, 3, 57, 34, 707351, tzinfo=utc), verbose_name='Date Created'),
            preserve_default=False,
        ),
    ]
