# Generated by Django 4.0 on 2022-02-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_finalcomment_date_created_reply_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalcomment',
            name='knowledge_scale',
        ),
        migrations.RemoveField(
            model_name='finalcomment',
            name='reason',
        ),
        migrations.AddField(
            model_name='reply',
            name='knowledge_scale',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='reason',
            field=models.CharField(default='', max_length=255),
        ),
    ]
