# Generated by Django 4.0 on 2022-02-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_remove_finalcomment_knowledge_scale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='technique',
        ),
    ]
