# Generated by Django 4.0 on 2022-02-11 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_remove_question_difficulty_remove_question_technique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='image',
        ),
    ]
