# Generated by Django 4.0 on 2022-02-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_remove_answer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='always',
            field=models.BooleanField(default=False, verbose_name='Always Ask'),
        ),
    ]
