# Generated by Django 4.0 on 2022-02-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_question_always'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalcomment',
            name='session',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reply',
            name='session',
            field=models.CharField(default='', max_length=255),
        ),
    ]
