# Generated by Django 4.0 on 2022-02-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_finalcomment_session_reply_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='knowledge_scale',
        ),
        migrations.AddField(
            model_name='finalcomment',
            name='certainty_sense',
            field=models.IntegerField(default=0),
        ),
    ]
